- name: package installation
  hosts: Jenkins-slave
  become: true

  roles:
    - Jenkins-slave

  tasks:
    - name: Ensure Docker service is restarted
      service:
        name: docker
        state: restarted
