- hosts: Jenkins-slave
  become: true  
  
  roles:
    - role: Jenkins-slave

  tasks:
    - name: Ensure Docker service is restarted
      service:
        name: docker
        state: restarted

    - name: Add jenkins and azureuser to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      become_method: sudo
      loop:
        - jenkins
        - azureuser
